# default configurations

# The default routes to collect data for if none are provided
default_routes:
  start_point: ""
  end_point: ""
  collect_return_trip: false

# Default scheduling cadences
schedule:
  study_duration_days: 14
  peak_interval_minutes: 5
  off_peak_interval_minutes: 30
  off_peak_start_time: "21:00"
  off_peak_end_time: "04:00"
